---
# TODO: Now we'll need to secure the machine first by editing the SSH config

# If this task is executed without having the ssh key properly configured the access to the machine is revoked.
# - name: Disable password authentication in the host machine
#   ansible.builtin.lineinfile:
#     path: /etc/ssh/ssh_config
#     regexp: '#PasswordAuthentication'
#     line: '#PasswordAuthentication no'
#     state: present

- name: Restart ssh_service to apply changes
  ansible.builtin.systemd_service:
    name: ssh.service
    state: restarted
    daemon_reload: true

- name: Configure Fail2ban
  ansible.builtin.template:
    src: roles/mastodon/templates/fail2ban_template.j2
    dest: /etc/fail2ban/jail.local
    mode: u=rw,g=r,o=r

- name: Restart Fail2ban service to apply changes
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
    daemon_reload: true

- name: Copy iptables configuration for ipv4
  ansible.builtin.copy:
    src: roles/mastodon/files/iptables-ipv4
    dest: /etc/iptables/rules.v4
    mode: u=rw,g=r,o=r

- name: Apply ipv4 configuration to iptables
  ansible.builtin.shell:
    cmd: iptables-restore < /etc/iptables/rules.v4

- name: Copy iptables configuration for ipv6
  ansible.builtin.copy:
    src: roles/mastodon/files/iptables-ipv6
    dest: /etc/iptables/rules.v6
    mode: u=rw,g=r,o=r

# TODO: See why the applied configuration is failing, if it causes to much problem, we can just ignore this anyway.
# - name: Apply ipv6 configuration to iptables
#   ansible.builtin.shell:
#     cmd: iptables-restore < /etc/iptables/rules.v6

- name: Configure PostgreSQL user for mastodon
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: mastodon
    state: present
    priv: CREATE
    db: mastodon_production

# - name: Grant database creation permission for mastodon user
#   become: true
#   become_user: postgres
#   community.postgresql.postgresql_privs:
#     db: mastodon_production
#     privs: CREATE
#     role: mastodon
#     objs: database

# TODO: We might need to do this using the expect module.
# - name: Generate Mastodon Configuration
#   become: true
#   become_user: mastodon
#   ansible.builtin.shell:
#     cmd: RAILS_ENV=production bundle exec rake mastodon:setup
#     executable: /bin/bash

# - name: Generate certificate
#   become: true
#   ansible.builtin.shell:
#     cmd: certbot certonly --nginx -d example.com
#     executable: /bin/bash


# - name: Extract external interfaces
#   become: true
#   ansible.builtin.shell: ip -br a | grep -oE 'enp[0-9]+s[0-9]+'
#   register: ip_output

# - name: Reboot system to apply changes
#   become: true
#   ansible.builtin.reboot:
