---
- name: Install all necessary dependencies
  ansible.builtin.include_tasks: install_dependencies.ansible.yml

- name: Perform initial configuration
  ansible.builtin.include_tasks: initial_configuration.ansible.yml
