---
- name: Restart ssh_service to apply changes
  ansible.builtin.systemd_service:
    name: ssh.service
    state: restarted
    daemon_reload: true

- name: Configure Fail2ban
  ansible.builtin.template:
    src: roles/mastodon/templates/fail2ban_template.j2
    dest: /etc/fail2ban/jail.local
    mode: u=rw,g=r,o=r

- name: Restart Fail2ban service to apply changes
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
    daemon_reload: true

- name: Copy iptables configuration for ipv4
  ansible.builtin.copy:
    src: roles/mastodon/files/iptables-ipv4
    dest: /etc/iptables/rules.v4
    mode: u=rw,g=r,o=r

- name: Apply ipv4 configuration to iptables
  ansible.builtin.shell:
    cmd: iptables-restore < /etc/iptables/rules.v4
  changed_when: false

- name: Copy iptables configuration for ipv6
  ansible.builtin.copy:
    src: roles/mastodon/files/iptables-ipv6
    dest: /etc/iptables/rules.v6
    mode: u=rw,g=r,o=r

# TODO: See why the applied configuration is failing, if it causes to much problem, we can just ignore this anyway.
# - name: Apply ipv6 configuration to iptables
#   ansible.builtin.shell:
#     cmd: iptables-restore < /etc/iptables/rules.v6

- name: Configure PostgreSQL
  ansible.builtin.include_tasks: postgresql_configuration.ansible.yml

- name: Check if .env.production file has been generated already
  ansible.builtin.stat:
    path: /home/mastodon/live/.env.production
  register: env_file

- name: Generate secrets
  ansible.builtin.include_tasks: secrets_config.ansible.yml
  when: not env_file.stat.exists

- name: Configure Mastodon | Copy template file into the target host
  ansible.builtin.template:
    src: roles/mastodon/templates/env.production.config.j2
    dest: /home/mastodon/live/.env.production
    owner: mastodon
    mode: u=rw,g=rw,o=r
  when: not env_file.stat.exists

- name: Configure Mastodon | Create database and database schema
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: bash -ilc 'bin/rails db:setup'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: db_schema_result
  when: database_exists.stdout_lines[0] == '0'
  changed_when: db_schema_result.rc == 0

- name: Configure Mastodon | Run assets precompilation
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: bash -ilc 'bin/rails assets:precompile'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: assets_precompile_result
  when: database_exists.stdout_lines[0] == '0'
  changed_when: assets_precompile_result.rc == 0

# TODO: This should be done using a certificate module since the command is interactive and could potentially generate incorrect configurations.
# - name: Generate certificate
#   become: true
#   ansible.builtin.shell:
#     cmd: "certbot certonly --nginx -d {{ mastodon_server_domain }}"

- name: Create Nginx configuration
  ansible.builtin.template:
    src: roles/mastodon/templates/nginx_config.j2
    dest: /etc/nginx/sites-available/mastodon
    mode: u=rw,g=rw,o=r

- name: Create link for nginx configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mastodon
    dest: /etc/nginx/sites-enabled/mastodon
    state: link

- name: Remove leftover file for Nginx
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    daemon_reload: true

- name: Copy systemd service templates from the Mastodon directory
  ansible.builtin.copy:
    remote_src: true
    src: /home/mastodon/live/dist/mastodon-sidekiq.service
    dest: /etc/systemd/system/
    mode: u=rw,g=rw,o=r

- name: Copy systemd service templates from the Mastodon directory
  ansible.builtin.copy:
    remote_src: true
    src: /home/mastodon/live/dist/mastodon-streaming.service
    dest: /etc/systemd/system/
    mode: u=rw,g=rw,o=r

- name: Copy systemd service templates from the Mastodon directory
  ansible.builtin.copy:
    remote_src: true
    src: /home/mastodon/live/dist/mastodon-streaming@.service
    dest: /etc/systemd/system/
    mode: u=rw,g=rw,o=r

- name: Copy systemd service templates from the Mastodon directory
  ansible.builtin.copy:
    remote_src: true
    src: /home/mastodon/live/dist/mastodon-web.service
    dest: /etc/systemd/system/
    mode: u=rw,g=rw,o=r

- name: Start Mastodon services
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
    state: started
  with_items:
    - mastodon-web
    - mastodon-sidekiq
    - mastodon-streaming

# The population of the indices is only done if the indices are empty (this is handled by tootctl)
- name: Create Elasticsearch indices and fill them
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: bash -ilc 'RAILS_ENV="production" bin/tootctl search deploy'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: elasticsearch_output
  changed_when: elasticsearch_output.rc == 0

- name: Create Admin account
  ansible.builtin.include_tasks: user_configuration.ansible.yml
