---
# - name: Create Mastodon PostgreSQL database
#   become: true
#   become_user: postgres
#   community.postgresql.postgresql_db:
#     name: mastodon_production
#     # login_user: mastodon
#     # login_host: localhost
#     login_password: "{{ mastodon_postgresql_password }}"
#     port: 5432


# - name: Configure PostgreSQL user for mastodon
#   become: true
#   become_user: postgres
#   community.postgresql.postgresql_user:
#     name: mastodon
#     db: mastodon_production
#     password: "{{ mastodon_postgresql_password }}"
#     # login_host: localhost
#     # login_user: mastodon
#     port: 5432
#     role_attr_flags: CREATEDB

# - name: Grant database creation permission for mastodon user
#   become: true
#   become_user: postgres
#   community.postgresql.postgresql_privs:
#     db: mastodon_production
#     privs: ALL
#     role: mastodon
#     type: database

- name: Check whether mastodon_production database exists already
  become: true
  ansible.builtin.shell:
    cmd: sudo -u postgres psql -l | grep mastodon_production | wc -l
  register: database_exists
  changed_when: false

# TODO: This should be done using the postgres module.
- name: Grant mastodon user permissions to create databases
  become: true
  ansible.builtin.shell:
    cmd: sudo -u postgres createuser mastodon --createdb
    executable: /bin/bash
  when: database_exists.stdout_lines[0] == '0'
  changed_when: database_exists.stdout_lines[0] == '0'
