---
- name: Generate secrets | SECRET_KEY_BASE
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: bash -ilc 'rake secret'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: secret_key_base

- name: Generate secrets | OTP_SECRET
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: bash -ilc 'rake secret'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: otp_secret

- name: Generate secrets | VAPID_PRIVATE_KEY
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: bash -ilc 'rake mastodon:webpush:generate_vapid_key'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: vapid_private_key

- name: Generate secrets | VAPID_PUBLIC_KEY
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: bash -ilc 'rake mastodon:webpush:generate_vapid_key'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: vapid_public_key
