---
- name: Generate SECRET_KEY_BASE secret
  become: true
  ansible.builtin.command: openssl rand -hex 64
  register: secret_key_base

- name: Generate OTP_SECRET secret
  become: true
  ansible.builtin.command: openssl rand -hex 64
  register: otp_secret

- name: Generate VAPID_PRIVATE_KEY
  become: true
  ansible.builtin.command: openssl ecparam -name prime256v1 -genkey -noout -out vapid_private_key.pem

- name: Generate VAPID_PUBLIC_KEY
  become: true
  ansible.builtin.command: openssl ec -in vapid_private_key.pem -pubout -out vapid_public_key.pem

- name: Trim generated VAPID_PRIVATE_KEY
  become: true
  ansible.builtin.shell: |
    cat vapid_private_key.pem | sed -e "1 d" -e "$ d" | tr -d "\n"
    echo
  register: vapid_private_key

- name: Trim generate VAPID_PUBLIC_KEY
  become: true
  ansible.builtin.shell: |
    cat vapid_public_key.pem | sed -e "1 d" -e "$ d" | tr -d "\n"
    echo
  register: vapid_public_key

- name: Generate PostgreSQL secret
  become: true
  ansible.builtin.command: openssl rand -hex 15
  register: postgresql_secret

- name: Generate elasticsearch secret
  become: true
  ansible.builtin.command: openssl rand -hex 15
  register: elasticsearch_secret

- name: Create file to store secrets
  become: true
  ansible.builtin.file:
    path: /opt/mastodon/secrets.txt
    state: touch

- name: Store generated secrets in the secrets file (SECRET_KEY_BASE)
  become: true
  ansible.builtin.lineinfile:
    path: /opt/mastodon/secrets.txt
    line: "SECRET_KEY_BASE={{ secret_key_base.stdout_lines[0] }}"
    regexp: '^SECRET_KEY_BASE='
    state: present

- name: Store generated secrets in the secrets file (OTP_SECRET)
  become: true
  ansible.builtin.lineinfile:
    path: /opt/mastodon/secrets.txt
    line: "OTP_SECRET={{ otp_secret.stdout_lines[0] }}"
    regexp: '^OTP_SECRET='
    state: present

- name: Store generated secrets in the secrets file (VAPID_PRIVATE_KEY)
  become: true
  ansible.builtin.lineinfile:
    path: /opt/mastodon/secrets.txt
    line: "VAPID_PRIVATE_KEY={{ vapid_private_key.stdout_lines[0] }}"
    regexp: '^VAPID_PRIVATE_KEY='
    state: present

- name: Store generated secrets in the secrets file (VAPID_PUBLIC_KEY)
  become: true
  ansible.builtin.lineinfile:
    path: /opt/mastodon/secrets.txt
    line: "VAPID_PUBLIC_KEY={{ vapid_public_key.stdout_lines[0] }}"
    regexp: '^VAPID_PUBLIC_KEY='
    state: present

- name: Store generated secrets in the secrets file (POSTGRESQL_SECRET)
  become: true
  ansible.builtin.lineinfile:
    path: /opt/mastodon/secrets.txt
    line: "POSTGRESQL_SECRET={{ postgresql_secret.stdout_lines[0] }}"
    regexp: '^POSTGRESQL_SECRET='
    state: present

- name: Store generated secrets in the secrets file (ELASTICSEARCH_SECRET)
  become: true
  ansible.builtin.lineinfile:
    path: /opt/mastodon/secrets.txt
    line: "ELASTICSEARCH_SECRET={{ elasticsearch_secret.stdout_lines[0] }}"
    regexp: '^ELASTICSEARCH_SECRET='
    state: present
