---
- name: Create password auxiliary file
  ansible.builtin.file:
    path: /home/mastodon/temporaryPassword.txt
    state: touch
    mode: u=rw

- name: Create admin user
  become: true
  become_user: mastodon
  ansible.builtin.shell:
    cmd: |
      bash -ilc 'RAILS_ENV=production bin/tootctl accounts create \
      {{ mastodon_admin_account_name }} \
      --email {{ mastodon_admin_email }} \
      --confirmed \
      --role Owner'
    executable: /bin/bash
    chdir: /home/mastodon/live
  register: password
  failed_when: false

- name: Save temporary password
  ansible.builtin.lineinfile:
    path: /home/mastodon/temporaryPassword.txt
    line: "{{ password.stdout_lines[1] }}"
  when: password.stdout is search("New password")
