---
- name: Initial ip configuration
  hosts: localhost
  become: true
  # We need to investigate a method for making sure the user is happy with the input they've provided.
  vars_prompt:
    - name: server_hostname
      prompt: "Enter the server hostname: "
      private: false

  tasks:
    - name: List external interfaces
      ansible.builtin.command: ip -br a
      register: ip_output
      changed_when: false

    - name: Extract external interfaces
      ansible.builtin.set_fact:
        external_interfaces: "{{ ip_output.stdout_lines | select('match', '.*\\s+UP\\s+.*') | map('regex_replace', '^([^\\s]+).*$', '\\1') | list }}"

    - name: Configure firewall
      ansible.posix.firewalld:
        zone: public
        interface: "{{ external_interfaces }}"
        permanent: true
        state: enabled
      # ansible.builtin.command: "sudo firewall-cmd --add-interface {{ item }} --zone public"
      # loop: "{{ external_interfaces }}"

    - name: Enable http service
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: true
        state: enabled
      # ansible.builtin.command: sudo firewall-cmd --add-service http --add-service https --zone public

    - name: Enable https service
      ansible.posix.firewalld:
        zone: public
        service: https
        permanent: true
        state: enabled

    - name: Ensure that docker interface is in a trusted zone
      ansible.posix.firewalld:
        zone: trusted
        interface: docker0
        permanent: true
        state: enabled
      # ansible.builtin.command: sudo firewall-cmd --add-interface=docker0 --zone trusted

    - name: Add masquerade
      ansible.posix.firewalld:
        zone: public
        masquerade: true
        permanent: true
        state: enabled
      # ansible.builtin.command: sudo firewall-cmd --zone=public --add-masquerade

    # - name: Make changes permanent
    #   ansible.builtin.command: sudo firewall-cmd --runtime-to-permanent

    # TODO: Make sure to check most of the commands with changed_when to avoid problems
    - name: Define server hostname
      ansible.builtin.command: "sudo hostnamectl --static set-hostname {{ server_hostname }}"

    - name: Increase limit of mmap counts
      ansible.builtin.shell: echo "vm.max_map_count=262144" | sudo tee /etc/sysctl.d/90-max_map_count.conf

    - name: Apply changes of limit in mmpa counts
      ansible.builtin.command: sudo sysctl --system

    - name: Create application directory
      ansible.builtin.file:
        path: /opt/mastodon
        state: directory
        recurse: true # This allows the creation of the parent directories if they don't exist

    - name: Create directories related to database operations (PostgreSQL)
      ansible.builtin.file:
        path: /opt/mastodon/database/postgresql
        state: directory
        recurse: true

    - name: Create directories related to database operations (Redis)
      ansible.builtin.file:
        path: /opt/mastodon/database/redis
        state: directory
        recurse: true

    - name: Create directories related to database operations (elasticsearch)
      ansible.builtin.file:
        path: /opt/mastodon/database/elasticsearch
        state: directory
        mode: '1000' # This changes the permissions in the directory
        recurse: true

    - name: Create directories related to web operations (public).
      ansible.builtin.file:
        path: /opt/mastodon/web/public
        state: directory
        mode: '991'
        recurse: true

    - name: Create directories related to web operations (system).
      ansible.builtin.file:
        path: /opt/mastodon/web/system
        state: directory
        mode: '991'
        recurse: true

    - name: Copy docker-compose file into the corresponding system directory
      ansible.builtin.command: cp ../docker-compose.yml /opt/mastodon/docker-compose.yml

    - name: Initialize empty application configuration (application.env)
      ansible.builtin.file:
        path: /opt/mastodon/application.env
        state: touch
        mode: '600'

    - name: Initialize empty application configuration (database.env)
      ansible.builtin.file:
        path: /opt/mastodon/database.env
        state: touch
        mode: '600'

    - name: Generate SECRET_KEY_BASE secret
      ansible.builtin.command: openssl rand -hex 64
      register: secret_key_base

    - name: Generate OTP_SECRET secret
      ansible.builtin.command: openssl rand -hex 64
      register: otp_secret

    - name: Generate VAPID_PRIVATE_KEY
      ansible.builtin.command: openssl ecparam -name prime256v1 -genkey -noout -out vapid_private_key.pem
      register: vapid_private_key

    - name: Generate VAPID_PUBLIC_KEY
      ansible.builtin.command: openssl ec -in vapid_private_key.pem -pubout -out vapid_public_key.pem
      register: vapid_public_key

    - name: Generate PostgreSQL secret
      ansible.builtin.command: openssl rand -hex 64
      register: postgresql_secret

    - name: Generate elasticsearch secret
      ansible.builtin.command: openssl rand -hex 64
      register: elasticsearch_secret

    - name: Create file to store secrets
      ansible.builtin.file:
        path: /opt/mastodon/secrets.txt
        state: touch

    - name: Store generated secrets in the secrets file
      ansible.builtin.lineinfile:
        path: /opt/mastodon/secrets.txt
        state: present
        with_items:
          - "SECRET_KEY_BASE={{ secret_key_base }}"
          - "OTP_SECRET={{ otp_secret }}"
          - "VAPID_PRIVATE_KEY={{ vapid_private_key }}"
          - "VAPID_PUBLIC_KEY={{ vapid_public_key }}"
          - "POSTGRESQL_SECRET={{ postgresql_secret }}"
          - "ELASTICSEARCH_SECRET={{ elasticsearch_secret }}"
