---
- name: Initial ip configuration
  hosts: localhost
  become: true
  # We need to investigate a method for making sure the user is happy with the input they've provided.
  vars_prompt:
    - name: server_hostname
      prompt: "Enter the server hostname: "
      private: false

  tasks:
    - name: List external interfaces
      ansible.builtin.command: ip -br a
      register: ip_output
      changed_when: false

    - name: Extract external interfaces
      ansible.set_fact:
        external_interfaces: "{{ ip_output.stdout_lines | select('match', '.*\\s+UP\\s+.*') | map('regex_replace', '^([^\\s]+).*$', '\\1') | list }}"

    - name: Configure firewall
      ansible.posix.firewalld:
        zone: public
        interface: "{{ external_interfaces }}"
        permanent: true
        state: enabled
      # ansible.builtin.command: "sudo firewall-cmd --add-interface {{ item }} --zone public"
      # loop: "{{ external_interfaces }}"

    - name: Enable http service
      ansible.posix.firewalld:
        zone: public
        service: http
        permanent: true
        state: enabled
      # ansible.builtin.command: sudo firewall-cmd --add-service http --add-service https --zone public

    - name: Enable https service
      ansible.posix.firewalld:
        zone: public
        service: https
        permanent: true
        state: enabled

    - name: Ensure that docker interface is in a trusted zone
      ansible.posix.firewalld:
        zone: trusted
        interface: docker0
        permanent: true
        state: enabled
      # ansible.builtin.command: sudo firewall-cmd --add-interface=docker0 --zone trusted

    - name: Add masquerade
      ansible.posix.firewalld:
        zone: public
        masquerade: true
        permanent: true
        state: enabled
      # ansible.builtin.command: sudo firewall-cmd --zone=public --add-masquerade

    # - name: Make changes permanent
    #   ansible.builtin.command: sudo firewall-cmd --runtime-to-permanent

    - name: Define server hostname
      ansible.builtin.command: "sudo hostnamectl --static set-hostname {{ server_hostname }}"

    - name: Increase limit of mmap counts
      ansible.builtin.shell: echo "vm.max_map_count=262144" | sudo tee /etc/sysctl.d/90-max_map_count.conf

    - name: Apply changes of limit in mmpa counts
      ansible.builtin.command: sudo sysctl --system

    - name: Create application directory
      file:
        path: /opt/mastodon
        state: directory
        recurse: yes # This allows the creation of the parent directories if they don't exist

    - name: Create directories related to database operations (PostgreSQL)
      file:
        path: /opt/mastodon/database/postgresql
        state: directory
        recurse: yes

    - name: Create directories related to database operations (Redis)
      file:
        path: /opt/mastodon/database/redis
        state: directory
        recurse: yes

    - name: Create directories related to database operations (elasticsearch)
      file:
        path: /opt/mastodon/database/elasticsearch
        state: directory
        mode: 1000 # This changes the permissions in the directory
        recurse: yes

    - name: Create directories related to web operations (public).
      file:
        path: /opt/mastodon/web/public
        state: directory
        mode: 991
        recurse: yes

    - name: Create directories related to web operations (system).
      file:
        path: /opt/mastodon/web/system
        state: directory
        mode: 991
        recurse: yes

    - name: Copy docker-compose file into the corresponding system directory
      ansible.builtin.command: cp ../docker-compose.yml /opt/mastodon/docker-compose.yml
